### ISSUE TITLE
.dotnet framework used to compile

### ISSUE THREAD

**Issue by Chomikmarkus** [aaaddress1/xlsGen#1]
My build fails in visual studio 2022, what silution of net framework used to generate it? 
Thanks

**Comment by Chomikmarkus** [comment]
Plus i am running into error when comilig that miss defaultmacrotemplatex

**Comment by aaaddress1** [comment]
> Plus i am running into error when comilig that miss defaultmacrotemplatex

is there any screenshots of compiling error? your question little bit ambiguous

**Comment by Chomikmarkus** [comment]
So tried ti compile it again to make screens to yoi! Build succeed but running it getting errors:
![Screenshot_20211128-091559](https://user-images.githubusercontent.com/92059377/143733454-44231897-252b-4345-aba2-cd0cba9c3556.png)
![Screenshot_20211128-091526](https://user-images.githubusercontent.com/92059377/143733455-a950a821-825d-4e2e-adfc-076245a9e301.png)

**Comment by aaaddress1** [comment]
> So tried ti compile it again to make screens to yoi! Build succeed but running it getting errors:
> 
> ![Screenshot_20211128-091559](https://user-images.githubusercontent.com/92059377/143733454-44231897-252b-4345-aba2-cd0cba9c3556.png)
> 
> ![Screenshot_20211128-091526](https://user-images.githubusercontent.com/92059377/143733455-a950a821-825d-4e2e-adfc-076245a9e301.png)
> 
> 

hey buddy, check the error code. 

you can see that xlsGen lack of defualt XL4 template at the same directory.

the code works well, but it crashed when running.

**Comment by Chomikmarkus** [comment]
Ough so stupid from me, gave it all files it needs and works fine! About commands is same like in macrome or it generates automatically output? Any configurables parameters??
